from psycopg2.extras import RealDictRow
db_mock = [RealDictRow([('id', 'a09a5e7d-aa13-451b-8086-9e35c0ac0fb0'),
              ('email', 'admin'),
              ('is_first_sign_in', False),
              ('students',
               [{'availability': {'friday': [],
                                  'monday': [{'end': '15:00',
                                              'start': '06:00',
                                              'type': 'school'}],
                                  'saturday': [],
                                  'sunday': [{'end': '15:00',
                                              'start': '06:00',
                                              'type': 'school'},
                                             {'end': '21:30',
                                              'start': '19:30',
                                              'type': 'sports'}],
                                  'thursday': [{'end': '15:00',
                                                'start': '06:00',
                                                'type': 'school'},
                                               {'end': '16:00',
                                                'start': '15:00',
                                                'type': 'others'},
                                               {'end': '22:15',
                                                'start': '20:15',
                                                'type': 'sports'}],
                                  'tuesday': [{'end': '15:00',
                                               'start': '06:00',
                                               'type': 'school'},
                                              {'end': '21:30',
                                               'start': '19:30',
                                               'type': 'sports'}],
                                  'wednesday': [{'end': '15:00',
                                                 'start': '06:00',
                                                 'type': 'school'}]},
                 'basicInfo': {'firstName': 'John',
                               'grade': '8',
                               'lastName': 'Doe'},
                 'id': 'e1d3498f-cca5-48dc-a977-e50e876668c8',
                 'subjects': [{'lessonsPerWeek': 2, 'name': 'Math'},
                              {'lessonsPerWeek': 1, 'name': 'Physics'},
                              {'lessonsPerWeek': 1, 'name': 'Chemistry'}]}])]),
 RealDictRow([('id', 'd4c17e60-08de-47c7-9ef0-33ae8aa442fb'),
              ('email', 'manalhasan857@gmail.com'),
              ('is_first_sign_in', False),
              ('students',
               [{'availability': {'friday': [],
                                  'monday': [{'end': '15:00',
                                              'start': '06:00',
                                              'type': 'school'}],
                                  'saturday': [],
                                  'sunday': [{'end': '15:00',
                                              'start': '06:00',
                                              'type': 'school'}],
                                  'thursday': [{'end': '15:00',
                                                'start': '06:00',
                                                'type': 'school'}],
                                  'tuesday': [{'end': '15:00',
                                               'start': '06:00',
                                               'type': 'school'},
                                              {'end': '19:00',
                                               'start': '16:30',
                                               'type': 'sports'},
                                              {'end': '23:59',
                                               'start': '21:00',
                                               'type': 'others'},
                                              {'end': '16:30',
                                               'start': '15:00',
                                               'type': 'others'},
                                              {'end': '07:00',
                                               'start': '00:00',
                                               'type': 'others'},
                                              {'end': '04:00',
                                               'start': '00:00',
                                               'type': 'others'}],
                                  'wednesday': [{'end': '15:00',
                                                 'start': '06:00',
                                                 'type': 'school'}]},
                 'basicInfo': {'firstName': 'Omran',
                               'grade': '8',
                               'lastName': 'Omran'},
                 'id': '6601c394-de69-4ba2-83b3-91e351313721',
                 'subjects': [{'lessonsPerWeek': 1, 'name': 'Math'},
                              {'lessonsPerWeek': 1, 'name': 'Physics'},
                              {'lessonsPerWeek': 1, 'name': 'Chemistry'},
                              {'lessonsPerWeek': 1, 'name': 'Biology'}]},
                {'availability': {'friday': [],
                                  'monday': [{'end': '15:00',
                                              'start': '06:00',
                                              'type': 'school'}],
                                  'saturday': [],
                                  'sunday': [{'end': '15:00',
                                              'start': '06:00',
                                              'type': 'school'}],
                                  'thursday': [{'end': '15:00',
                                                'start': '06:00',
                                                'type': 'school'}],
                                  'tuesday': [{'end': '15:00',
                                               'start': '06:00',
                                               'type': 'school'},
                                              {'end': '16:45',
                                               'start': '15:00',
                                               'type': 'others'},
                                              {'end': '19:00',
                                               'start': '17:00',
                                               'type': 'sports'},
                                              {'end': '23:30',
                                               'start': '21:00',
                                               'type': 'others'}],
                                  'wednesday': [{'end': '15:00',
                                                 'start': '06:00',
                                                 'type': 'school'}]},
                 'basicInfo': {'firstName': 'Mila',
                               'grade': '8',
                               'lastName': 'Omran'},
                 'id': '6881f03b-1624-4a33-8430-9face0ce6fb3',
                 'subjects': [{'lessonsPerWeek': 1, 'name': 'Math'},
                              {'lessonsPerWeek': 1, 'name': 'Physics'},
                              {'lessonsPerWeek': 1, 'name': 'Chemistry'},
                              {'lessonsPerWeek': 1, 'name': 'Biology'}]}])])]


db_mock2 =  [
    RealDictRow(
        {'id': 'a09a5e7d-aa13-451b-8086-9e35c0ac0fb0', 
         'email': 'admin', 
         'is_first_sign_in': False, 
         'students': [
             {'id': 'e1d3498f-cca5-48dc-a977-e50e876668c8', 
              'subjects': [{'name': 'Math', 'lessonsPerWeek': 2}, 
                           {'name': 'Physics', 'lessonsPerWeek': 1}, 
                           {'name': 'Chemistry', 'lessonsPerWeek': 1}], 
              'basicInfo': {'grade': '8', 'lastName': 'Doe', 'firstName': 'John'},
              'availability': {'friday': [], 
                               'monday': [
                                   {'end': '15:00', 'type': 'school', 'start': '06:00'}
                                   ], 
                               'sunday': [
                                   {'end': '15:00', 'type': 'school', 'start': '06:00'},
                                   {'end': '21:30', 'type': 'sports', 'start': '19:30'}
                                   ],
                               'tuesday': [
                                   {'end': '15:00', 'type': 'school', 'start': '06:00'},
                                   {'end': '21:30', 'type': 'sports', 'start': '19:30'}], 'saturday': [], 'thursday': [{'end': '15:00', 'type': 'school', 'start': '06:00'}, {'end': '16:00', 'type': 'others', 'start': '15:00'}, {'end': '22:15', 'type': 'sports', 'start': '20:15'}], 'wednesday': [{'end': '15:00', 'type': 'school', 'start': '06:00'}]}}]})]
