from psycopg2.extras import RealDictRow

db_mock = RealDictRow([('id', 'a09a5e7d-aa13-451b-8086-9e35c0ac0fb0'),
              ('email', 'admin'),
              ('is_first_sign_in', False),
              ('students',
               [{'availability': {'friday': [{'end': '05:00',
                                              'start': '22:00',
                                              'type': 'sleep'}],
                                  'monday': [{'end': '05:00',
                                              'start': '22:00',
                                              'type': 'sleep'},
                                             {'end': '15:00',
                                              'start': '06:00',
                                              'type': 'school'},
                                             {'end': '22:00',
                                              'start': '20:00',
                                              'type': 'sports'}],
                                  'saturday': [{'end': '05:00',
                                                'start': '22:00',
                                                'type': 'sleep'}],
                                  'sunday': [{'end': '05:00',
                                              'start': '22:00',
                                              'type': 'sleep'},
                                             {'end': '15:00',
                                              'start': '06:00',
                                              'type': 'school'},
                                             {'end': '20:45',
                                              'start': '18:45',
                                              'type': 'sports'}],
                                  'thursday': [{'end': '05:00',
                                                'start': '22:00',
                                                'type': 'sleep'},
                                               {'end': '15:00',
                                                'start': '06:00',
                                                'type': 'school'},
                                               {'end': '19:00',
                                                'start': '18:00',
                                                'type': 'others'}],
                                  'tuesday': [{'end': '05:00',
                                               'start': '22:00',
                                               'type': 'sleep'},
                                              {'end': '15:00',
                                               'start': '06:00',
                                               'type': 'school'}],
                                  'wednesday': [{'end': '05:00',
                                                 'start': '22:00',
                                                 'type': 'sleep'},
                                                {'end': '15:00',
                                                 'start': '06:00',
                                                 'type': 'school'},
                                                {'end': '19:15',
                                                 'start': '17:15',
                                                 'type': 'sports'}]},
                 'basicInfo': {'firstName': 'Jane',
                               'grade': '8',
                               'lastName': 'Doe'},
                 'id': '8b7d4aa5-6d64-4c4b-8aa5-2708df7eed76',
                 'subjects': [{'lessonsPerWeek': 2,
                               'name': 'Math',
                               'sharedWith': ['b0b20e4b-8c1f-4ca5-9b30-8b7903fb3935']},
                              {'lessonsPerWeek': 1,
                               'name': 'Physics',
                               'sharedWith': ['b0b20e4b-8c1f-4ca5-9b30-8b7903fb3935']},
                              {'lessonsPerWeek': 1,
                               'name': 'Chemistry',
                               'sharedWith': ['b0b20e4b-8c1f-4ca5-9b30-8b7903fb3935']}]},
                {'availability': {'friday': [{'end': '05:00',
                                              'start': '21:30',
                                              'type': 'sleep'},
                                             {'end': '15:30',
                                              'start': '06:00',
                                              'type': 'school'}],
                                  'monday': [{'end': '05:00',
                                              'start': '21:30',
                                              'type': 'sleep'},
                                             {'end': '15:30',
                                              'start': '06:00',
                                              'type': 'school'}],
                                  'saturday': [{'end': '05:00',
                                                'start': '21:30',
                                                'type': 'sleep'},
                                               {'end': '15:30',
                                                'start': '06:00',
                                                'type': 'school'}],
                                  'sunday': [{'end': '05:00',
                                              'start': '21:30',
                                              'type': 'sleep'},
                                             {'end': '15:30',
                                              'start': '06:00',
                                              'type': 'school'},
                                             {'end': '19:45',
                                              'start': '18:45',
                                              'type': 'sports'}],
                                  'thursday': [{'end': '05:00',
                                                'start': '21:30',
                                                'type': 'sleep'},
                                               {'end': '15:30',
                                                'start': '06:00',
                                                'type': 'school'},
                                               {'end': '18:30',
                                                'start': '16:30',
                                                'type': 'sports'}],
                                  'tuesday': [{'end': '05:00',
                                               'start': '21:30',
                                               'type': 'sleep'},
                                              {'end': '15:30',
                                               'start': '06:00',
                                               'type': 'school'},
                                              {'end': '20:45',
                                               'start': '18:45',
                                               'type': 'sports'}],
                                  'wednesday': [{'end': '05:00',
                                                 'start': '21:30',
                                                 'type': 'sleep'},
                                                {'end': '15:30',
                                                 'start': '06:00',
                                                 'type': 'school'},
                                                {'end': '18:45',
                                                 'start': '16:45',
                                                 'type': 'others'}]},
                 'basicInfo': {'firstName': 'John',
                               'grade': '8',
                               'lastName': 'Doe'},
                 'id': 'b0b20e4b-8c1f-4ca5-9b30-8b7903fb3935',
                 'subjects': [{'lessonsPerWeek': 2,
                               'name': 'Math',
                               'sharedWith': ['8b7d4aa5-6d64-4c4b-8aa5-2708df7eed76']},
                              {'lessonsPerWeek': 1,
                               'name': 'Physics',
                               'sharedWith': ['8b7d4aa5-6d64-4c4b-8aa5-2708df7eed76']},
                              {'lessonsPerWeek': 1,
                               'name': 'Chemistry',
                               'sharedWith': ['8b7d4aa5-6d64-4c4b-8aa5-2708df7eed76']}]}])]),

db_mock2 = [RealDictRow([('id', 'a09a5e7d-aa13-451b-8086-9e35c0ac0fb0'),
              ('email', 'admin'),
              ('is_first_sign_in', False),
              ('students',
               [{'availability': {'friday': [{'end': '05:00',
                                              'start': '22:00',
                                              'type': 'sleep'}],
                                  'monday': [{'end': '05:00',
                                              'start': '22:00',
                                              'type': 'sleep'},
                                             {'end': '15:30',
                                              'start': '06:00',
                                              'type': 'school'},
                                             {'end': '19:45',
                                              'start': '18:45',
                                              'type': 'sports'}],
                                  'saturday': [{'end': '05:00',
                                                'start': '22:00',
                                                'type': 'sleep'}],
                                  'sunday': [{'end': '05:00',
                                              'start': '22:00',
                                              'type': 'sleep'},
                                             {'end': '15:30',
                                              'start': '06:00',
                                              'type': 'school'},
                                             {'end': '20:15',
                                              'start': '18:15',
                                              'type': 'sports'}],
                                  'thursday': [{'end': '05:00',
                                                'start': '22:00',
                                                'type': 'sleep'},
                                               {'end': '15:30',
                                                'start': '06:00',
                                                'type': 'school'},
                                               {'end': '20:00',
                                                'start': '18:00',
                                                'type': 'sports'}],
                                  'tuesday': [{'end': '05:00',
                                               'start': '22:00',
                                               'type': 'sleep'},
                                              {'end': '15:30',
                                               'start': '06:00',
                                               'type': 'school'},
                                              {'end': '17:00',
                                               'start': '16:00',
                                               'type': 'others'}],
                                  'wednesday': [{'end': '05:00',
                                                 'start': '22:00',
                                                 'type': 'sleep'},
                                                {'end': '15:30',
                                                 'start': '06:00',
                                                 'type': 'school'}]},
                 'basicInfo': {'firstName': 'Jane',
                               'grade': '8',
                               'lastName': 'Doe'},
                 'id': '378347b3-422a-4809-847a-5ff17f538d16',
                 'subjects': [{'lessonsPerWeek': 2,
                               'name': 'Math',
                               'sharedWith': ['b0bf1ce3-042c-4e6e-9b8b-408392e3c1ed']},
                              {'lessonsPerWeek': 1,
                               'name': 'Physics',
                               'sharedWith': ['b0bf1ce3-042c-4e6e-9b8b-408392e3c1ed']},
                              {'lessonsPerWeek': 1,
                               'name': 'Chemistry',
                               'sharedWith': ['b0bf1ce3-042c-4e6e-9b8b-408392e3c1ed']}]},
                {'availability': {'friday': [{'end': '05:00',
                                              'start': '23:00',
                                              'type': 'sleep'}],
                                  'monday': [{'end': '05:00',
                                              'start': '23:00',
                                              'type': 'sleep'},
                                             {'end': '16:00',
                                              'start': '06:00',
                                              'type': 'school'}],
                                  'saturday': [{'end': '05:00',
                                                'start': '23:00',
                                                'type': 'sleep'}],
                                  'sunday': [{'end': '05:00',
                                              'start': '23:00',
                                              'type': 'sleep'},
                                             {'end': '16:00',
                                              'start': '06:00',
                                              'type': 'school'},
                                             {'end': '21:00',
                                              'start': '20:00',
                                              'type': 'others'}],
                                  'thursday': [{'end': '05:00',
                                                'start': '23:00',
                                                'type': 'sleep'},
                                               {'end': '16:00',
                                                'start': '06:00',
                                                'type': 'school'},
                                               {'end': '18:30',
                                                'start': '17:30',
                                                'type': 'sports'}],
                                  'tuesday': [{'end': '05:00',
                                               'start': '23:00',
                                               'type': 'sleep'},
                                              {'end': '16:00',
                                               'start': '06:00',
                                               'type': 'school'},
                                              {'end': '20:15',
                                               'start': '19:15',
                                               'type': 'sports'}],
                                  'wednesday': [{'end': '05:00',
                                                 'start': '23:00',
                                                 'type': 'sleep'},
                                                {'end': '16:00',
                                                 'start': '06:00',
                                                 'type': 'school'}]},
                 'basicInfo': {'firstName': 'John',
                               'grade': '8',
                               'lastName': 'Doe'},
                 'id': 'b0bf1ce3-042c-4e6e-9b8b-408392e3c1ed',
                 'subjects': [{'lessonsPerWeek': 2,
                               'name': 'Math',
                               'sharedWith': []},
                              {'lessonsPerWeek': 1,
                               'name': 'Physics',
                               'sharedWith': []},
                              {'lessonsPerWeek': 1,
                               'name': 'Chemistry',
                               'sharedWith': []}]}])]),
 RealDictRow([('id', 'd4c17e60-08de-47c7-9ef0-33ae8aa442fb'),
              ('email', 'manalhasan857@gmail.com'),
              ('is_first_sign_in', False),
              ('students',
               [{'availability': {'friday': [{'end': '06:00',
                                              'start': '21:00',
                                              'type': 'sleep'}],
                                  'monday': [{'end': '15:00',
                                              'start': '06:00',
                                              'type': 'school'},
                                             {'end': '06:00',
                                              'start': '21:00',
                                              'type': 'sleep'}],
                                  'saturday': [{'end': '06:00',
                                                'start': '21:00',
                                                'type': 'sleep'}],
                                  'sunday': [{'end': '15:00',
                                              'start': '06:00',
                                              'type': 'school'},
                                             {'end': '06:00',
                                              'start': '21:00',
                                              'type': 'sleep'}],
                                  'thursday': [{'end': '15:00',
                                                'start': '06:00',
                                                'type': 'school'},
                                               {'end': '06:00',
                                                'start': '21:00',
                                                'type': 'sleep'}],
                                  'tuesday': [{'end': '15:00',
                                               'start': '06:00',
                                               'type': 'school'},
                                              {'end': '16:45',
                                               'start': '15:00',
                                               'type': 'others'},
                                              {'end': '19:00',
                                               'start': '17:00',
                                               'type': 'sports'},
                                              {'end': '23:30',
                                               'start': '21:00',
                                               'type': 'others'},
                                              {'end': '06:00',
                                               'start': '21:00',
                                               'type': 'sleep'}],
                                  'wednesday': [{'end': '15:00',
                                                 'start': '06:00',
                                                 'type': 'school'},
                                                {'end': '06:00',
                                                 'start': '21:00',
                                                 'type': 'sleep'}]},
                 'basicInfo': {'firstName': 'Mila',
                               'grade': '8',
                               'lastName': 'Omran'},
                 'id': '6881f03b-1624-4a33-8430-9face0ce6fb3',
                 'subjects': [{'lessonsPerWeek': 1, 'name': 'Math',
                               'sharedWith': []},
                              {'lessonsPerWeek': 1, 'name': 'Physics',
                               'sharedWith': []},
                              {'lessonsPerWeek': 1, 'name': 'Chemistry',
                               'sharedWith': []},
                              {'lessonsPerWeek': 1, 'name': 'Biology',
                               'sharedWith': []}]},
                {'availability': {'friday': [{'end': '06:00',
                                              'start': '21:00',
                                              'type': 'sleep'}],
                                  'monday': [{'end': '15:00',
                                              'start': '06:00',
                                              'type': 'school'},
                                             {'end': '06:00',
                                              'start': '21:00',
                                              'type': 'sleep'}],
                                  'saturday': [{'end': '06:00',
                                                'start': '21:00',
                                                'type': 'sleep'}],
                                  'sunday': [{'end': '15:00',
                                              'start': '06:00',
                                              'type': 'school'},
                                             {'end': '06:00',
                                              'start': '21:00',
                                              'type': 'sleep'}],
                                  'thursday': [{'end': '15:00',
                                                'start': '06:00',
                                                'type': 'school'},
                                               {'end': '06:00',
                                                'start': '21:00',
                                                'type': 'sleep'}],
                                  'tuesday': [{'end': '15:00',
                                               'start': '06:00',
                                               'type': 'school'},
                                              {'end': '19:00',
                                               'start': '16:30',
                                               'type': 'sports'},
                                              {'end': '23:59',
                                               'start': '21:00',
                                               'type': 'others'},
                                              {'end': '16:30',
                                               'start': '15:00',
                                               'type': 'others'},
                                              {'end': '07:00',
                                               'start': '00:00',
                                               'type': 'others'},
                                              {'end': '04:00',
                                               'start': '00:00',
                                               'type': 'others'},
                                              {'end': '06:00',
                                               'start': '21:00',
                                               'type': 'sleep'}],
                                  'wednesday': [{'end': '15:00',
                                                 'start': '06:00',
                                                 'type': 'school'},
                                                {'end': '06:00',
                                                 'start': '21:00',
                                                 'type': 'sleep'}]},
                 'basicInfo': {'firstName': 'Omran',
                               'grade': '8',
                               'lastName': 'Omran'},
                 'id': '6601c394-de69-4ba2-83b3-91e351313721',
                 'subjects': [{'lessonsPerWeek': 1, 'name': 'Math',
                               'sharedWith': []},
                              {'lessonsPerWeek': 1, 'name': 'Physics',
                               'sharedWith': []},
                              {'lessonsPerWeek': 1, 'name': 'Chemistry',
                               'sharedWith': []},
                              {'lessonsPerWeek': 1, 'name': 'Biology',
                               'sharedWith': []},
                               ]}])])]

db_mock3 = [RealDictRow([('id', 'a09a5e7d-aa13-451b-8086-9e35c0ac0fb0'),
              ('email', 'admin'),
              ('is_first_sign_in', False),
              ('students',
               [{'availability': {'friday': [],
                                  'monday': [{'end': '15:00',
                                              'start': '06:00',
                                              'type': 'school'}],
                                  'saturday': [],
                                  'sunday': [{'end': '15:00',
                                              'start': '06:00',
                                              'type': 'school'},
                                             {'end': '21:30',
                                              'start': '19:30',
                                              'type': 'sports'}],
                                  'thursday': [{'end': '15:00',
                                                'start': '06:00',
                                                'type': 'school'},
                                               {'end': '16:00',
                                                'start': '15:00',
                                                'type': 'others'},
                                               {'end': '22:15',
                                                'start': '20:15',
                                                'type': 'sports'}],
                                  'tuesday': [{'end': '15:00',
                                               'start': '06:00',
                                               'type': 'school'},
                                              {'end': '21:30',
                                               'start': '19:30',
                                               'type': 'sports'}],
                                  'wednesday': [{'end': '15:00',
                                                 'start': '06:00',
                                                 'type': 'school'}]},
                 'basicInfo': {'firstName': 'John',
                               'grade': '8',
                               'lastName': 'Doe'},
                 'id': 'e1d3498f-cca5-48dc-a977-e50e876668c8',
                 'subjects': [{'lessonsPerWeek': 2, 'name': 'Math'},
                              {'lessonsPerWeek': 1, 'name': 'Physics'},
                              {'lessonsPerWeek': 1, 'name': 'Chemistry'}]}])]),
 RealDictRow([('id', 'd4c17e60-08de-47c7-9ef0-33ae8aa442fb'),
              ('email', 'manalhasan857@gmail.com'),
              ('is_first_sign_in', False),
              ('students',
               [{'availability': {'friday': [],
                                  'monday': [{'end': '15:00',
                                              'start': '06:00',
                                              'type': 'school'}],
                                  'saturday': [],
                                  'sunday': [{'end': '15:00',
                                              'start': '06:00',
                                              'type': 'school'}],
                                  'thursday': [{'end': '15:00',
                                                'start': '06:00',
                                                'type': 'school'}],
                                  'tuesday': [{'end': '15:00',
                                               'start': '06:00',
                                               'type': 'school'},
                                              {'end': '19:00',
                                               'start': '16:30',
                                               'type': 'sports'},
                                              {'end': '23:59',
                                               'start': '21:00',
                                               'type': 'others'},
                                              {'end': '16:30',
                                               'start': '15:00',
                                               'type': 'others'},
                                              {'end': '07:00',
                                               'start': '00:00',
                                               'type': 'others'},
                                              {'end': '04:00',
                                               'start': '00:00',
                                               'type': 'others'}],
                                  'wednesday': [{'end': '15:00',
                                                 'start': '06:00',
                                                 'type': 'school'}]},
                 'basicInfo': {'firstName': 'Omran',
                               'grade': '8',
                               'lastName': 'Omran'},
                 'id': '6601c394-de69-4ba2-83b3-91e351313721',
                 'subjects': [{'lessonsPerWeek': 1, 'name': 'Math'},
                              {'lessonsPerWeek': 1, 'name': 'Physics'},
                              {'lessonsPerWeek': 1, 'name': 'Chemistry'},
                              {'lessonsPerWeek': 1, 'name': 'Biology'}]},
                {'availability': {'friday': [],
                                  'monday': [{'end': '15:00',
                                              'start': '06:00',
                                              'type': 'school'}],
                                  'saturday': [],
                                  'sunday': [{'end': '15:00',
                                              'start': '06:00',
                                              'type': 'school'}],
                                  'thursday': [{'end': '15:00',
                                                'start': '06:00',
                                                'type': 'school'}],
                                  'tuesday': [{'end': '15:00',
                                               'start': '06:00',
                                               'type': 'school'},
                                              {'end': '16:45',
                                               'start': '15:00',
                                               'type': 'others'},
                                              {'end': '19:00',
                                               'start': '17:00',
                                               'type': 'sports'},
                                              {'end': '23:30',
                                               'start': '21:00',
                                               'type': 'others'}],
                                  'wednesday': [{'end': '15:00',
                                                 'start': '06:00',
                                                 'type': 'school'}]},
                 'basicInfo': {'firstName': 'Mila',
                               'grade': '8',
                               'lastName': 'Omran'},
                 'id': '6881f03b-1624-4a33-8430-9face0ce6fb3',
                 'subjects': [{'lessonsPerWeek': 1, 'name': 'Math'},
                              {'lessonsPerWeek': 1, 'name': 'Physics'},
                              {'lessonsPerWeek': 1, 'name': 'Chemistry'},
                              {'lessonsPerWeek': 1, 'name': 'Biology'}]}])])]


db_mock4 =  [
    RealDictRow(
        {'id': 'a09a5e7d-aa13-451b-8086-9e35c0ac0fb0', 
         'email': 'admin', 
         'is_first_sign_in': False, 
         'students': [
             {'id': 'e1d3498f-cca5-48dc-a977-e50e876668c8', 
              'subjects': [{'name': 'Math', 'lessonsPerWeek': 2}, 
                           {'name': 'Physics', 'lessonsPerWeek': 1}, 
                           {'name': 'Chemistry', 'lessonsPerWeek': 1}], 
              'basicInfo': {'grade': '8', 'lastName': 'Doe', 'firstName': 'John'},
              'availability': {'friday': [], 
                               'monday': [
                                   {'end': '15:00', 'type': 'school', 'start': '06:00'}
                                   ], 
                               'sunday': [
                                   {'end': '15:00', 'type': 'school', 'start': '06:00'},
                                   {'end': '21:30', 'type': 'sports', 'start': '19:30'}
                                   ],
                               'tuesday': [
                                   {'end': '15:00', 'type': 'school', 'start': '06:00'},
                                   {'end': '21:30', 'type': 'sports', 'start': '19:30'}], 'saturday': [], 'thursday': [{'end': '15:00', 'type': 'school', 'start': '06:00'}, {'end': '16:00', 'type': 'others', 'start': '15:00'}, {'end': '22:15', 'type': 'sports', 'start': '20:15'}], 'wednesday': [{'end': '15:00', 'type': 'school', 'start': '06:00'}]}}]})]
